"""Export a colored point-cloud PLY as a pseudo-Gaussian 3DGS PLY."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import numpy as np

SH_DC_CONSTANT = 0.28209479177387814


def gaussian_vertex_dtype() -> np.dtype:
    """Return the binary layout used by standard 3D Gaussian Splat PLY files."""
    fields: list[tuple[str, str]] = [
        ("x", "<f4"),
        ("y", "<f4"),
        ("z", "<f4"),
        ("nx", "<f4"),
        ("ny", "<f4"),
        ("nz", "<f4"),
        ("f_dc_0", "u1"),
        ("f_dc_1", "u1"),
        ("f_dc_2", "u1"),
    ]
    fields.extend((f"f_rest_{index}", "u1") for index in range(45))
    fields.extend(
        (
            ("opacity", "<f4"),
            ("scale_0", "<f4"),
            ("scale_1", "<f4"),
            ("scale_2", "<f4"),
            ("rot_0", "<f4"),
            ("rot_1", "<f4"),
            ("rot_2", "<f4"),
            ("rot_3", "<f4"),
        )
    )
    return np.dtype(fields)


def rgb_to_sh_dc(rgb: np.ndarray) -> np.ndarray:
    """Encode linear RGB values as the DC term used by 3DGS viewers."""
    values = np.asarray(rgb, dtype=np.float64) / 255.0
    if values.ndim != 2 or values.shape[-1] != 3:
        raise ValueError(f"Expected RGB values with shape [N,3], got {values.shape}")
    sh_dc = (values - 0.5) / SH_DC_CONSTANT
    encoded = np.rint((sh_dc + 1.0) * 127.5)
    return np.clip(encoded, 0, 255).astype(np.uint8)


def gaussian_vertex_data(
    points: np.ndarray, colors: np.ndarray, radius: float, opacity: float
) -> np.ndarray:
    """Create isotropic, opaque-ish Gaussians from colored points."""
    points = np.asarray(points, dtype=np.float32)
    colors = np.asarray(colors, dtype=np.float64)
    if points.ndim != 2 or points.shape[-1] != 3:
        raise ValueError(f"Expected points with shape [N,3], got {points.shape}")
    if colors.shape != points.shape:
        raise ValueError(
            f"Color shape {colors.shape} does not match point shape {points.shape}"
        )
    if radius <= 0:
        raise ValueError("radius must be positive")
    if not 0.0 < opacity < 1.0:
        raise ValueError("opacity must be between 0 and 1, exclusive")

    vertices = np.zeros(len(points), dtype=gaussian_vertex_dtype())
    vertices["x"], vertices["y"], vertices["z"] = points.T
    vertices["f_dc_0"], vertices["f_dc_1"], vertices["f_dc_2"] = rgb_to_sh_dc(
        colors
    ).T
    vertices["opacity"] = np.log(opacity / (1.0 - opacity))
    log_radius = np.log(radius)
    vertices["scale_0"] = log_radius
    vertices["scale_1"] = log_radius
    vertices["scale_2"] = log_radius
    vertices["rot_0"] = 1.0
    return vertices


def write_binary_gaussian_ply(path: Path, vertices: np.ndarray) -> None:
    """Write a binary little-endian standard 3DGS PLY."""
    if vertices.dtype != gaussian_vertex_dtype():
        raise TypeError("vertices do not use the Gaussian PLY dtype")
    dtype = gaussian_vertex_dtype()
    properties: list[str] = []
    for name in dtype.names:
        field = dtype[name]
        if field == np.dtype("<f4"):
            properties.append(f"property float {name}")
        elif field == np.dtype("u1"):
            properties.append(f"property uchar {name}")
        else:
            raise TypeError(f"Unsupported Gaussian PLY field type for {name}: {field}")

    header = "\n".join(
        (
            "ply",
            "format binary_little_endian 1.0",
            "comment Generated by ABot-Recon pseudo-Gaussian preview",
            f"element vertex {len(vertices)}",
            *properties,
            "end_header",
        )
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as handle:
        handle.write((header + "\n").encode("ascii"))
        handle.write(memoryview(vertices).cast("B"))


def point_budget_indices(point_count: int, max_points: int) -> np.ndarray:
    if max_points < 0:
        raise ValueError("max_points must be non-negative")
    if max_points == 0 or point_count <= max_points:
        return np.arange(point_count, dtype=np.int64)
    if max_points == 1:
        return np.array([point_count // 2], dtype=np.int64)
    return np.linspace(0, point_count - 1, max_points, dtype=np.int64)


def world_to_y_up_transform() -> np.ndarray:
    transform = np.eye(4, dtype=np.float64)
    transform[1, 1] = -1.0
    transform[2, 2] = -1.0
    return transform


def import_open3d() -> Any:
    try:
        import open3d as o3d
    except ImportError as error:
        raise SystemExit(
            "Open3D is required to read the input PLY. Install it with:\n"
            "  python -m pip install open3d"
        ) from error
    return o3d


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a colored point cloud to a pseudo-Gaussian 3DGS preview."
    )
    parser.add_argument("--input", type=Path, required=True, help="Input RGB point PLY")
    parser.add_argument("--output", type=Path, required=True, help="Output 3DGS PLY")
    parser.add_argument(
        "--voxel", type=float, default=0.2, help="Voxel downsampling size in meters"
    )
    parser.add_argument(
        "--max-points", type=int, default=1_500_000, help="Point budget; 0 keeps all"
    )
    parser.add_argument(
        "--radius", type=float, default=0.18, help="Isotropic Gaussian radius in meters"
    )
    parser.add_argument(
        "--opacity", type=float, default=0.85, help="Gaussian opacity in (0,1)"
    )
    parser.add_argument(
        "--flip-y",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Map camera-style Y-down/Z-forward axes to Y-up viewer coordinates",
    )
    return parser.parse_args(argv)


def validate_args(args: argparse.Namespace) -> None:
    if not args.input.is_file():
        raise SystemExit(f"Input PLY does not exist: {args.input}")
    if args.voxel < 0:
        raise SystemExit("--voxel must be non-negative")
    if args.max_points < 0:
        raise SystemExit("--max-points must be non-negative")
    if args.radius <= 0:
        raise SystemExit("--radius must be positive")
    if not 0.0 < args.opacity < 1.0:
        raise SystemExit("--opacity must be between 0 and 1, exclusive")


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    validate_args(args)
    o3d = import_open3d()

    print(f"Loading {args.input}")
    cloud = o3d.io.read_point_cloud(str(args.input))
    if not cloud.has_points():
        raise SystemExit(f"No points found in {args.input}")
    if not cloud.has_colors():
        cloud.paint_uniform_color([0.65, 0.68, 0.72])
    if args.voxel > 0:
        cloud = cloud.voxel_down_sample(args.voxel)
    indices = point_budget_indices(len(cloud.points), args.max_points)
    if len(indices) != len(cloud.points):
        cloud = cloud.select_by_index(indices)
    if args.flip_y:
        cloud.transform(world_to_y_up_transform())

    points = np.asarray(cloud.points, dtype=np.float32)
    colors = np.asarray(cloud.colors, dtype=np.float64) * 255.0
    vertices = gaussian_vertex_data(
        points, colors, radius=args.radius, opacity=args.opacity
    )
    write_binary_gaussian_ply(args.output, vertices)
    print(
        f"Wrote {args.output}: {len(vertices):,} pseudo-Gaussians | "
        f"radius={args.radius:.3f} m | opacity={args.opacity:.2f}"
    )


if __name__ == "__main__":
    main()
